# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               XY'S BLOG
tagline:             "learn more."
description:         "coding."
url:                 https://monkeyxy.github.io/
baseurl:             ''
paginate:            1

# About/contact
author:
  name:              kakachan
  url:               https://github.com/monkeyxy
  email:             791009808@qq.com

# Custom vars
version:             1.0.0

# Gems
gems:                [jekyll-paginate]
